# Generated by Django 4.1.2 on 2022-10-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuangong1', '0002_alter_user_info_passwd_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=111, verbose_name='生日'),
            preserve_default=False,
        ),
    ]
