# Generated by Django 4.1.2 on 2022-10-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuangong1', '0003_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
