# Generated by Django 4.1.2 on 2022-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuangong1', '0004_remove_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='passwd',
            field=models.IntegerField(max_length=64, verbose_name='密码'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
