# Generated by Django 4.1.2 on 2022-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuangong1', '0005_alter_user_info_passwd_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='passwd',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
