# Generated by Django 4.1.2 on 2022-10-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuangong1', '0006_alter_user_info_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone_num_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.DecimalField(decimal_places=2, default=99.0, max_digits=10, verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(0, '闲置'), (1, '被占用')], verbose_name='状态')),
                ('level', models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], verbose_name='级别')),
            ],
        ),
        migrations.AlterField(
            model_name='user_info',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuangong1.department', verbose_name='部门'),
        ),
    ]
