# Generated by Django 4.1.2 on 2022-10-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuangong1', '0007_phone_num_info_alter_user_info_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_num_info',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '闲置'), (1, '占用')], verbose_name='状态'),
        ),
    ]
