# Generated by Django 4.1.2 on 2022-11-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuangong1', '0008_alter_phone_num_info_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='dev_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(max_length=32, verbose_name='设备类型')),
            ],
        ),
        migrations.CreateModel(
            name='things_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things_source', models.CharField(max_length=32, verbose_name='请求来源')),
            ],
        ),
    ]
